import xarray as xr
import matplotlib.pyplot as plt
import numpy as np

In [2]:
con_ssh1 = xr.open_dataset("/mnt/e/CMIP5_ForM_noTauu/OBS/zos1/Con_SSH.nc")[
    'ssh'].loc["1871-01":"2019-12"].rolling(time=3,center=True).mean()[1:-1]
hadisst = xr.open_dataset("/mnt/e/CMIP5_ForM_noTauu/OBS/tos1/HadISST_sst_2x2.nc")[
    'sst'].loc["1871-01":"2019-12"].rolling(time=3,center=True).mean()[1:-1]
nino34 = xr.open_dataset("/mnt/e/CMIP5_ForM_noTauu/OBS/nino341/HadISST_sst_2x2.nc")[
    'sst'].loc["1871-01":"2019-12", 0,0].rolling(time=3,center=True).mean()[1:-1]


In [3]:
con_ssh1.time

<xarray.DataArray 'time' (time: 1786)>
array(['1871-02-16T00:00:00.000000000', '1871-03-16T00:00:00.000000000',
       '1871-04-16T00:00:00.000000000', ..., '2019-09-16T00:00:00.000000000',
       '2019-10-16T00:00:00.000000000', '2019-11-16T00:00:00.000000000'],
      dtype='datetime64[ns]')
Coordinates:
  * time     (time) datetime64[ns] 1871-02-16 1871-03-16 ... 2019-11-16
Attributes:
    standard_name:  time
    axis:           T

In [4]:
con_ssh1.shape,hadisst.shape,nino34.shape

((1786, 24, 72), (1786, 24, 72), (1786,))

In [5]:
con_ssh1.loc["1980":].time

<xarray.DataArray 'time' (time: 479)>
array(['1980-01-16T00:00:00.000000000', '1980-02-16T00:00:00.000000000',
       '1980-03-16T00:00:00.000000000', ..., '2019-09-16T00:00:00.000000000',
       '2019-10-16T00:00:00.000000000', '2019-11-16T00:00:00.000000000'],
      dtype='datetime64[ns]')
Coordinates:
  * time     (time) datetime64[ns] 1980-01-16 1980-02-16 ... 2019-11-16
Attributes:
    standard_name:  time
    axis:           T

In [6]:
con_ssh1.lon,con_ssh1.lat

(<xarray.DataArray 'lon' (lon: 72)>
 array([  0.,   5.,  10.,  15.,  20.,  25.,  30.,  35.,  40.,  45.,  50.,  55.,
         60.,  65.,  70.,  75.,  80.,  85.,  90.,  95., 100., 105., 110., 115.,
        120., 125., 130., 135., 140., 145., 150., 155., 160., 165., 170., 175.,
        180., 185., 190., 195., 200., 205., 210., 215., 220., 225., 230., 235.,
        240., 245., 250., 255., 260., 265., 270., 275., 280., 285., 290., 295.,
        300., 305., 310., 315., 320., 325., 330., 335., 340., 345., 350., 355.])
 Coordinates:
   * lon      (lon) float64 0.0 5.0 10.0 15.0 20.0 ... 340.0 345.0 350.0 355.0
 Attributes:
     standard_name:  longitude
     long_name:      longitude
     units:          degrees_east
     axis:           X,
 <xarray.DataArray 'lat' (lat: 24)>
 array([-55., -50., -45., -40., -35., -30., -25., -20., -15., -10.,  -5.,   0.,
          5.,  10.,  15.,  20.,  25.,  30.,  35.,  40.,  45.,  50.,  55.,  60.])
 Coordinates:
   * lat      (lat) float64 -55.0 -50.0 -45.0 

In [5]:
print(con_ssh1.loc["1980":].time[0])
var_ssh = np.array(con_ssh1.loc["1980":].fillna(0))
var_sst = np.array(hadisst.loc["1980":].fillna(0))
var_nino = np.array(nino34.loc["1980":].fillna(0))
np.save("../data/var_data/sst",var_sst)
np.save("../data/var_data/ssh",var_ssh)
np.save("../data/var_data/nino34",var_nino)
var_ssh.shape,var_nino.shape,var_sst.shape


<xarray.DataArray 'time' ()>
array('1980-01-16T00:00:00.000000000', dtype='datetime64[ns]')
Coordinates:
    time     datetime64[ns] 1980-01-16
Attributes:
    standard_name:  time
    axis:           T


((479, 24, 72), (479,), (479, 24, 72))

In [7]:
True in np.isnan(var_ssh)
# var_sst[-1]

False

In [8]:
nino34.loc[:"1979"]

<xarray.DataArray 'sst' (time: 1307)>
array([-0.3394127 , -0.39915466, -0.40410742, ...,  0.46997198,
        0.5159143 ,  0.5773392 ], dtype=float32)
Coordinates:
  * time     (time) datetime64[ns] 1871-02-15 ... 1979-12-16T12:00:00
    lon      float64 0.0
    lat      float64 0.0
Attributes:
    standard_name:  sea_surface_temperature
    long_name:      sst
    units:          C
    cell_methods:   time: lat: lon: mean

In [9]:
print(con_ssh1.loc[:"1979"].fillna(0).time[0])
train_ssh = np.array(con_ssh1.loc[:"1979"].fillna(0))
train_sst = np.array(hadisst.loc[:"1979"].fillna(0))
train_nino = np.array(nino34.loc[:"1979"].fillna(0))
np.save("../data/train_data/obs/sst", train_sst)
np.save("../data/train_data/obs/ssh", train_ssh)
np.save("../data/train_data/obs/nino34", train_nino)
train_ssh.shape, train_nino.shape, train_sst.shape


<xarray.DataArray 'time' ()>
array('1871-02-16T00:00:00.000000000', dtype='datetime64[ns]')
Coordinates:
    time     datetime64[ns] 1871-02-16
Attributes:
    standard_name:  time
    axis:           T


((1307, 24, 72), (1307,), (1307, 24, 72))

In [13]:
import os
nino34_path="/mnt/e/CMIP5_ForM_noTauu/nino341"
tos_path = "/mnt/e/CMIP5_ForM_noTauu/tos1"
zos_path = "/mnt/e/CMIP5_ForM_noTauu/zos1"
data_ls = os.listdir(nino34_path)

for fname in data_ls:
    print("="*40)
    model_name = fname.split("_")[2]
    print(model_name,":",fname)
    fname1 = list(fname)
    fname1[0] = "z"
    fname1 = "".join(fname1)
    zos_loc = zos_path + "/" + fname1
    tos_loc = tos_path + "/" + fname
    nino_loc = nino34_path + "/" + fname
    nino34 = xr.open_dataset(nino_loc)['tos'][:,0,0].rolling(time=3,center=True).mean()[1:-1].fillna(0)
    zos = xr.open_dataset(zos_loc)['zos'].rolling(time=3,center=True).mean()[1:-1].fillna(0)
    tos = xr.open_dataset(tos_loc)['tos'].rolling(time=3,center=True).mean()[1:-1].fillna(0)
    print("begin_month:",zos.time[0].dt.month.item())
    if zos.time[0].dt.month.item() != 2:
        print("Fake!")
    train_sst = np.array(tos)
    train_ssh = np.array(zos)
    train_nino = np.array(nino34)
    print(nino34.shape,zos.shape,tos.shape)
    # os.mkdir('../data/train_data/%s'%model_name)
    # print("success mkdir", '../data/train_data/%s'%model_name)
    # np.save("../data/train_data/%s/sst"%model_name, train_sst)
    # np.save("../data/train_data/%s/ssh"%model_name, train_ssh)
    # np.save("../data/train_data/%s/nino34"%model_name, train_nino)



ACCESS-CM2 : tos_Omon_ACCESS-CM2_historical_r1i1p1f1_185001-201412.nc1
begin_month: 2
(1978,) (1978, 24, 72) (1978, 24, 72)
CanESM2 : tos_Omon_CanESM2_historical_r1i1p1_185001-200512_reg.nc
begin_month: 2
(1870,) (1870, 24, 72) (1870, 24, 72)
CCSM4 : tos_Omon_CCSM4_historical_r1i1p1_185001-200512_reg.nc
begin_month: 2
(1870,) (1870, 24, 72) (1870, 24, 72)
CESM1-CAM5 : tos_Omon_CESM1-CAM5_historical_r1i1p1_185001-200512_reg.nc
begin_month: 2
(1870,) (1870, 24, 72) (1870, 24, 72)
CESM2 : tos_Omon_CESM2_historical_r1i1p1f1_185001-201412.nc1
begin_month: 2
(1978,) (1978, 24, 72) (1978, 24, 72)
CMCC-CESM : tos_Omon_CMCC-CESM_historical_r1i1p1_185001-200512_reg.nc
begin_month: 2
(1870,) (1870, 24, 72) (1870, 24, 72)
CMCC-CMS : tos_Omon_CMCC-CMS_historical_r1i1p1_185001-200512_reg.nc
begin_month: 2
(1870,) (1870, 24, 72) (1870, 24, 72)
CMCC-CM : tos_Omon_CMCC-CM_historical_r1i1p1_185001-200512_reg.nc
begin_month: 2
(1870,) (1870, 24, 72) (1870, 24, 72)
CNRM-CM5 : tos_Omon_CNRM-CM5_historical_